### ISSUE TITLE
Component on Backend Gives Error

### ISSUE THREAD

**Issue by nathancolquhoun** [todordev/ITPGoogleSearch#2]
When clicking on component in backend (Joomla 3) the administrator interface does not show and I just get this

Warning: require_once(/home/liveinla/public_html/administrator/components/com_itpgooglesearchDSlibrariesDSinit.php) [function.require-once]: failed to open stream: No such file or directory in /home/liveinla/public_html/administrator/components/com_itpgooglesearch/itpgooglesearch.php on line 17

Fatal error: require_once() [function.require]: Failed opening required '/home/liveinla/public_html/administrator/components/com_itpgooglesearchDSlibrariesDSinit.php' (include_path='.:/usr/lib/php') in /home/liveinla/public_html/administrator/components/com_itpgooglesearch/itpgooglesearch.php on line 17

**Comment by todordev** [comment]
Hi,
Thank you very much for the post!
I've just fixed it.
You can download latest version now.
http://itprism.com/free-joomla-extensions/others/google-search-integration
