### ISSUE TITLE
autocomplete is not work on module

### ISSUE THREAD

**Issue by jzeng808** [todordev/ITPGoogleSearch#3]
autocomplete function is not work on the module input. but it does work on the result page search input. Is there a way to eliminate the search input form on the result page? I don't want double search input area on the page.

**Comment by todordev** [comment]
Hi,
Thank you for the post.
I added a new option that you can use to hide the field.
You can download the latest version now.
http://itprism.com/free-joomla-extensions/others/google-search-integration
