### ISSUE TITLE
Missing option to stop links opening a new window

### ISSUE THREAD

**Issue by Sawtaytoes** [todordev/ITPGoogleSearch#4]
Hi! All the links in the ITP Google Search plugin open in a new window when clicked. Is there a workaround or menu option I haven't seen which changes this behavior so all links open up on the site itself?

**Comment by todordev** [comment]
Thank you for the post!

I have just added an option. It is part of release 2.5.
You can download it from here.
http://itprism.com/free-joomla-extensions/others/google-search-integration
