### ISSUE TITLE
Error on J3.2

### ISSUE THREAD

**Issue by freelancerteam** [todordev/ITPGoogleSearch#5]
Get an error on J.3.2

Strict Standards: Declaration of ITPGoogleSearchController::display() should be compatible with JControllerLegacy::display($cachable = false, $urlparams = Array) in ....../administrator/components/com_itpgooglesearch/controller.php on line 38

As well when using module it will not get to result page anf the URl shows someting like .../index.php?gsquery=&lang=en

thanks

**Comment by todordev** [comment]
fixed
